export const licencias = [
  {
    id: 1,
    ofi: 'OFI01',
    usuario_ant: 'Michael Lovon',
    usuario_act: 'Gabriel Tello',
    estado: 'Ocupado',
    empresa_usuario: 'R010 - El S.A.',
    empresa_licencia: 'R010 - El S.A.',
    puesto: 'Eccomerce',
    periodo: '2020',
    oc: 'OC-2024-001',
  },
  {
    id: 2,
    ofi: 'OFI02',
    usuario_ant: 'Luis Garcia',
    usuario_act: 'Joel Condori',
    estado: 'Ocupado',
    empresa_usuario: 'R010 - El S.A.',
    empresa_licencia: 'R010 - El S.A.',
    puesto: 'Producto',
    periodo: '2023',
    oc: 'OC-2024-001',
  },
  {
    id: 3,
    ofi: 'OFI03',
    usuario_ant: 'Juan Quispe',
    usuario_act: 'Juan Quispe',
    estado: 'Ocupado',
    empresa_usuario: 'R010 - El S.A.',
    empresa_licencia: 'R010 - El S.A.',
    puesto: 'Jefe de línea',
    periodo: '2023',
    oc: 'OC-2024-002',
  },
  {
    id: 4,
    ofi: 'OFI04',
    usuario_ant: 'Pamela Marca',
    usuario_act: 'Luis Medina',
    estado: 'Ocupado',
    empresa_usuario: 'R010 - El S.A.',
    empresa_licencia: 'R010 - El S.A.',
    puesto: 'Jefe de compras',
    periodo: '2024',
    oc: 'OC-2024-002',
  },
  {
    id: 5,
    ofi: 'OFI05',
    usuario_ant: 'Renzo Limachi',
    usuario_act: 'Juan Cahuana',
    estado: 'Ocupado',
    empresa_usuario: 'R010 - El S.A.',
    empresa_licencia: 'R010 - El S.A.',
    puesto: 'Practicante Producto',
    periodo: '2024',
    oc: 'OC-2024-002',
  },
  {
    id: 6,
    ofi: 'OFI06',
    usuario_ant: 'Silvia Blas',
    usuario_act: 'Angie Montesinos',
    estado: 'Ocupado',
    empresa_usuario: 'R010 - El S.A.',
    empresa_licencia: 'R010 - El S.A.',
    puesto: 'Jefe de compras',
    periodo: '2024',
    oc: 'OC-2024-003',
  },
  {
    id: 7,
    ofi: 'OFI07',
    usuario_ant: 'Alexander Rodriguez',
    usuario_act: 'Eduardo Razuri',
    estado: 'Ocupado',
    empresa_usuario: 'S090 - Tandem',
    empresa_licencia: 'S090 - Panorama CSC',
    puesto: 'Asistente de producto / TI',
    periodo: '2024',
    oc: 'OC-2024-003',
  },
  {
    id: 8,
    ofi: 'OFI08',
    usuario_ant: 'Ivette SD',
    usuario_act: 'Server 138',
    estado: 'Ocupado',
    empresa_usuario: 'S090 - Tandem',
    empresa_licencia: 'S090 - Panorama CSC',
    puesto: 'SISTEMAS - soporte',
    periodo: '2024',
    oc: 'OC-2024-003',
  },
  {
    id: 9,
    ofi: 'OFI09',
    usuario_ant: '—',
    usuario_act: '—',
    estado: 'Libre',
    empresa_usuario: '—',
    empresa_licencia: '—',
    puesto: '—',
    periodo: '—',
    oc: '—',
  },
  {
    id: 10,
    ofi: 'OFI10',
    usuario_ant: 'Carlos Mamani',
    usuario_act: '—',
    estado: 'Libre',
    empresa_usuario: 'R010 - El S.A.',
    empresa_licencia: 'R010 - El S.A.',
    puesto: 'Analista',
    periodo: '2023',
    oc: 'OC-2023-008',
  },
];

export const empresas = [
  'R010 - El S.A.',
  'S090 - Tandem',
  'S090 - Panorama CSC',
];

export const ocs = [
  'OC-2024-001',
  'OC-2024-002',
  'OC-2024-003',
  'OC-2023-008',
];
